arm_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - joint_1
    - joint_2
    - joint_3
    - joint_4
    - joint_5
    - joint_6
  constraints:
    goal_time: 0.6
    stopped_velocity_tolerance: 0.05
    joint_1: {trajectory: 0.1, goal: 0.1}
    joint_2: {trajectory: 0.1, goal: 0.1}
    joint_3: {trajectory: 0.1, goal: 0.1}
    joint_4: {trajectory: 0.1, goal: 0.1}
    joint_5: {trajectory: 0.1, goal: 0.1}
    joint_6: {trajectory: 0.1, goal: 0.1}
  stop_trajectory_duration: 0.5
  state_publish_rate:  25
  action_monitor_rate: 10


Gripper_Finger1_position_controller:
  type: effort_controllers/JointPositionController
  joint: Gripper_Finger1
  pid: {p: 100.0, i: 0.01, d: 10.0}
Gripper_Finger2_position_controller:
  type: effort_controllers/JointPositionController
  joint: Gripper_Finger2
  pid: {p: 100.0, i: 0.01, d: 10.0}
Gripper_Finger3_position_controller:
  type: effort_controllers/JointPositionController
  joint: Gripper_Finger3
  pid: {p: 100.0, i: 0.01, d: 10.0}              